/hik_cam_driver:
  ros__parameters:
    hik_cam_id: 0
    frame_id: hik_cam
    image_width: 1440
    image_height: 1080
    exposure_time: 4000
    exposure_gain: 7
    exposure_gain_b: 0
    exposure_gain_g: 0
    exposure_gain_r: 0
    balance_b: 1690
    balance_g: 1024
    balance_r: 2022
    debug: true
    using_shared_memory: false
    save_video: false

/daheng_cam_driver:
  ros__parameters:
    daheng_cam_id: 1
    frame_id: daheng_cam
    image_width: 1280
    image_height: 1024
    width_scale: 1
    height_scale: 1
    exposure_time: 6000
    exposure_gain: 14
    exposure_gain_b: 0
    exposure_gain_g: 0
    exposure_gain_r: 0
    balance_b: 1.56
    balance_g: 1.0
    balance_r: 1.548
    debug: true
    using_shared_memory: false
    save_video: false
    
/usb_cam_driver:
  ros__parameters:
    camera_id: 0
    frame_id: usb_cam
    image_width: 480
    image_height: 480
    fps: 30
    debug: true
    using_shared_memory: false
    using_video: true
    # video_path: "src/camera_driver/recorder/video/still_gyro.avi"
    # video_path: "src/camera_driver/recorder/video/gyro1.avi"
    video_path: "src/camera_driver/recorder/video/buff.webm"
    save_video: false

/mvs_cam_driver:
  ros__parameters:
    mvs_cam_id: 0
    frame_id: mvs_cam
  
/serialport:
  ros__parameters:
    debug_without_com: true
    baud: 115200
