# 哨兵上云台
MV_Sentry:
    #内参矩阵
    Intrinsic: [3626.5098590324505,  0.000000000000,  689.1283950373454,
                0.000000000000,  3626.285156056285,  582.7004766963166,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.04251601401350153, 0.963321415304225, 0.0, -0.0009602427973179668, -0.006641239457517189]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,-0.05,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [-1.5, -1.75]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 60

    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [ 0.02617095,   0.99945437,  -0.02015029,  -0.00043464,
            0.1181205,   -0.02310774,  -0.99273037,   0.00326701,
            -0.99265433,  0.02360054, -0.1186608,  -0.00323944,
            0,          0,          0,          1        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [ 0.02617095,   0.1181205,   -0.99265433, -0.00359017,
            0.99945437,  -0.02310774,   0.02360054,  0.00058635,
            -0.02015029, -0.99273037,  -0.1186608,   0.00285011,
            0,          0,          0,         1       ]
    #陀螺仪至云台转轴中心平移向量 R_g = R_i - T_iw
    T_iw: [-0.03, -0.05, -0.02]

# 哨兵下云台
KE0200110076:
    #内参矩阵
    Intrinsic: [1673.885947,  0.000000000000,  649.000553,
                0.000000000000,  1678.230815,  483.866587,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.059247, 0.042376, 0, 0.001615, 0.000831]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [0.5,0.3]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 60

    # 陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [ 0.0106869, 0.99950186, -0.02969544, 0,
            0.01352137, 0.02954998, 0.99947185, 0.1458,
            0.99985147, -0.01108278, -0.01319884, -0.13,
            0,              0,              0,              1]
    # 相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [ 0.0106869, 0.01352137, 0.99985147, 0.13,
            0.99950186, 0.02954998, -0.01108278, -0,
            -0.02969544, 0.99947185, -0.01319884, -0.1458,
            0,            0,              0,              1]
    #陀螺仪至云台转轴中心平移向量 R_g = R_i - T_iw
    T_iw: [0.02549, 0, -0.09566]

# 4号步兵
KE0200110075:
    #陀螺仪坐标系：枪口反方向为x轴正向，弹舱舵机右侧为y轴正向，垂直向上为z轴正向
    #内参矩阵
    Intrinsic:  [1675.042871,    0.000000000000,  623.481121,
                 0.000000000000, 1674.696037,     556.002821,
                 0.000000000000, 0.000000000000,  1.000000000000]
    Coeff: [-0.06719080320827164, 0.08771589756714641, 0.0, 0.0009056377800116876, -0.004604447207374161] 
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度 left- down-
    angle_offset: [0,0]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci:  [-0.00687597 , 0.9999657 ,  0.0046184  , 0.00935481,
            0.0005452  , 0.00462226, -0.99998917 , 0.00111573,
            -0.99997621 ,-0.00687337, -0.00057697 ,-0.00203505,
            0         , 0        ,  0         , 1.        ]
    T_ic: [-0.00687597,  0.0005452 , -0.99997621, -0.00197128,
            0.9999657 ,  0.00462226, -0.00687337, -0.00937364,
            0.0046184 , -0.99998917, -0.00057697, 0.00107134,
            0         ,  0         , 0          ,  1.        ]
    #陀螺仪至云台转轴中心平移向量 R_g = R_i - T_iw
    T_iw: [-0.1, 0, -0.05]

# 英雄
KE0200110073:
    #内参矩阵
    Intrinsic: [1718.36539,  0.000000000000,  653.14109,
                0.000000000000,  1721.55294,   503.95899,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.05401, 0.316969, 0.0, 0.000108, 0.0]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [-0.5, 0.5]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [ 0.14947211, 0.05626111, 0.98716401, 0.06231027,
           -0.98876234, 0.01119973, 0.14907582, 0.17142281,
           -0.0026688, -0.99835327, 0.05730291, -0.08664204,  
            0          ,0           ,0            ,1        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [ 0.14947211, -0.98876234, -0.0026688, 0.15995154,
            0.05626111, 0.01119973, -0.99835327, -0.0919249,
           0.98716401, 0.14907582, 0.05730291, -0.08210061,
            0          ,0           ,0           ,1        ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0.02, 0.01, -0.05]

# 3号步兵
KE0200110074:
    #内参矩阵
    Intrinsic: [1673.424472385629,  0.000000000000,  637.8832545589809,
                0.000000000000,  1675.7985620485485,  504.2286845853391,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.058880415613303524, 0.09971916846980647, 0, -0.002214233751008686, 0.0003401562523311091]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [-0.5, 0.5]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [ 0.00741479 ,0.99653649  ,-0.08282545 ,0.01111486,
           -0.04520383 ,-0.08240902 ,-0.99557288 ,0.00670747,
           -0.99895027 ,0.01112599  ,0.04443622  ,-0.077358,  
            0          ,0           ,0            ,1        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [ 0.00741479 ,-0.04520383 ,-0.99895027 ,-0.07705601,
            0.99653649 ,-0.08240902 , 0.01112599 ,-0.00966292,
           -0.08282545 ,-0.99557288 , 0.04443622 , 0.01103587,
            0          ,0           ,0           ,1        ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0, 0, -0.02]

# 5号blancer步兵
00J90630561:
    #内参矩阵
    Intrinsic: [1797.2975789010106,  0.000000000000,  723.6001872526609,
                0.000000000000, 1797.6519520606107, 538.6252723443785,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.2242896874114463, 0.20266017480965967, 0.0, -0.0006348790946737486, -0.001781986001710534]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [-1,3.0]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [-0.9985929  , 0.05302462,  0.00078463, -0.02610757,
           -0.00180485 ,-0.0191954, -0.99981412,  0.07643799,
           -0.05299971 ,-0.9984087,  0.01926414, -0.11042897,
            0.         , 0.       ,  0.        ,  1.        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [-0.9985929  ,-0.00180485 ,-0.05299971 ,-0.03178557,
            0.05302462, -0.01919545, -0.9984087 , -0.10740164,
            0.00078463, -0.99981412,  0.01926414,  0.07857158,
            0.        ,  0.        ,  0.        ,  1.        ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0, 0, -0.02]