/hik_cam_driver:
  ros__parameters:
    hik_cam_id: 0
    image_width: 1440
    image_height: 1080
    exposure_time: 4000
    exposure_gain: 7
    exposure_gain_b: 0
    exposure_gain_g: 0
    exposure_gain_r: 0
    balance_b: 1690
    balance_g: 1024
    balance_r: 2022
    debug: true

/daheng_cam_driver:
  ros__parameters:
    daheng_cam_id: 1
    image_width: 1080
    image_height: 1024
    width_scale: 1
    height_scale: 1
    exposure_time: 6000
    exposure_gain: 14
    exposure_gain_b: 0
    exposure_gain_g: 0
    exposure_gain_r: 0
    balance_b: 1.56
    balance_g: 1.0
    balance_r: 1.548
    debug: true
    
/usb_cam_driver:
  ros__parameters:
    camera_id: 0
    frame_id: usb_cam
    image_width: 480
    image_height: 480
    fps: 30
    debug: true